version: '3.4'
services:

  viade:
    container_name: viade
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    labels:
      NAME: "viade"
  solidserver:
    container_name: solid-server
    image: nodesolidserver/node-solid-server
    volumes:
      - ./volumes/soliddata:/usr/src/app/data
      - ./volumes/soliddb:/usr/src/app/.db
    ports:
      - "8443:8443"
      
volumes:
  soliddata:
    external: false
  soliddb:
    external: false
